In [ ]:
# M24CA1L306 Data Science Lab - Lab Exercise #06
# Student: Abhinav | MAC25MCA-2002 | S3 MCA (2025-27)
# Dataset: iris.csv
# Task: kNN using sklearn - KNeighborsClassifier and KNeighborsRegressor

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import (
    accuracy_score, classification_report,
    confusion_matrix
)

In [2]:
# ─────────────────────────────────────────────
# Load and prepare data
# ─────────────────────────────────────────────
df = pd.read_csv("Iris.csv")
df.drop(columns=["Id"], inplace=True)

X = df[["SepalLengthCm", "SepalWidthCm", "PetalLengthCm", "PetalWidthCm"]].values

# Encode species labels to integers (0, 1, 2)
le = LabelEncoder()
y_class = le.fit_transform(df["Species"])       # for classification

# Scale features - kNN is distance-based, so scaling matters
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

In [3]:
# ─────────────────────────────────────────────
# Train/Test Split
# ─────────────────────────────────────────────
X_train, X_test, y_train_cls, y_test_cls = train_test_split(
    X_scaled, y_class, test_size=0.2, random_state=42, stratify=y_class
)


In [ ]:
# ─────────────────────────────────────────────
# KNeighborsClassifier
# ─────────────────────────────────────────────
print("=" * 50)
print("KNeighborsClassifier (k=5)")
print("=" * 50)

knn_clf = KNeighborsClassifier(n_neighbors=5, metric="euclidean")
knn_clf.fit(X_train, y_train_cls)
y_pred = knn_clf.predict(X_test)

print(f"Accuracy: {accuracy_score(y_test_cls, y_pred):.4f}")
print(classification_report(y_test_cls, y_pred, target_names=le.classes_))
print(confusion_matrix(y_test_cls, y_pred))

# Predict new instance
new = scaler.transform([[5.1, 3.5, 1.4, 0.2]])
print("Predicted:", le.inverse_transform(knn_clf.predict(new))[0])
print("Probabilities:", dict(zip(le.classes_, knn_clf.predict_proba(new)[0].round(3))))

KNeighborsClassifier (k=5)
Accuracy       : 0.9333

Classification Report:
                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        10
Iris-versicolor       0.83      1.00      0.91        10
 Iris-virginica       1.00      0.80      0.89        10

       accuracy                           0.93        30
      macro avg       0.94      0.93      0.93        30
   weighted avg       0.94      0.93      0.93        30

Confusion Matrix:
[[10  0  0]
 [ 0 10  0]
 [ 0  2  8]]

New instance (raw)  : [5.1 3.5 1.4 0.2]
Predicted class     : Iris-setosa
Class probabilities : {'Iris-setosa': np.float64(1.0), 'Iris-versicolor': np.float64(0.0), 'Iris-virginica': np.float64(0.0)}


In [5]:

# ─────────────────────────────────────────────
# Effect of k on classifier accuracy
# ─────────────────────────────────────────────
print("\n" + "=" * 50)
print("Accuracy vs k (KNeighborsClassifier)")
print("=" * 50)
for k in [1, 3, 5, 7, 9, 11]:
    clf_k = KNeighborsClassifier(n_neighbors=k)
    clf_k.fit(X_train, y_train_cls)
    acc = accuracy_score(y_test_cls, clf_k.predict(X_test))
    print(f"  k={k:2d}  ->  Accuracy: {acc:.4f}")


Accuracy vs k (KNeighborsClassifier)
  k= 1  ->  Accuracy: 0.9667
  k= 3  ->  Accuracy: 0.9333
  k= 5  ->  Accuracy: 0.9333
  k= 7  ->  Accuracy: 0.9667
  k= 9  ->  Accuracy: 0.9667
  k=11  ->  Accuracy: 0.9667
