In [25]:
import pandas as pd
import numpy as np
import matplotlib as plt
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB

In [26]:
df = pd.read_csv("../Datasets/iris/Iris.csv")
df=df.drop(df.columns[0],axis=1)
print(df.describe())
print(df.isnull().sum())

       SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count     150.000000    150.000000     150.000000    150.000000
mean        5.843333      3.054000       3.758667      1.198667
std         0.828066      0.433594       1.764420      0.763161
min         4.300000      2.000000       1.000000      0.100000
25%         5.100000      2.800000       1.600000      0.300000
50%         5.800000      3.000000       4.350000      1.300000
75%         6.400000      3.300000       5.100000      1.800000
max         7.900000      4.400000       6.900000      2.500000
SepalLengthCm    0
SepalWidthCm     0
PetalLengthCm    0
PetalWidthCm     0
Species          0
dtype: int64


In [27]:
ratios=[(0.1,"90-10"),(0.2,"80-20"),(0.3,"70-30"),(0.4,"60-40")]
le=LabelEncoder()
df['Species']=le.fit_transform(df['Species'])

In [29]:
X=df.drop(df.columns[-1],axis=1)
y=df['Species']
for test_s,text in ratios:
    X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=test_s,random_state=42)
    gnb=GaussianNB()
    gnb.fit(X_train,y_train)
    pred=gnb.predict(X_test)
    print(f"Classfication report for {text} split\n {classification_report(y_test,pred)}")
    print(f"Confusion matrix for {text} split\n {confusion_matrix(y_test,pred)}")
    print(f"Accuracy for {text} split = {accuracy_score(y_test,pred)}\n\n")
    print("_"*100)

Classfication report for 90-10 split
               precision    recall  f1-score   support

           0       1.00      1.00      1.00         6
           1       1.00      1.00      1.00         6
           2       1.00      1.00      1.00         3

    accuracy                           1.00        15
   macro avg       1.00      1.00      1.00        15
weighted avg       1.00      1.00      1.00        15

Confusion matrix for 90-10 split
 [[6 0 0]
 [0 6 0]
 [0 0 3]]
Accuracy for 90-10 split = 1.0


____________________________________________________________________________________________________
Classfication report for 80-20 split
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.