In [ ]:
import pandas as pd
import numpy as np
import matplotlib as plt
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB

In [ ]:
df=pd.read_csv('../Datasets/Wine_Quality.csv')
print(df.columns)
print(df.isnull().sum())
print(df.describe())
df.dropna(inplace=True)
print(df.isnull().sum())
df.describe()

Index(['type', 'fixed acidity', 'volatile acidity', 'citric acid',
       'residual sugar', 'chlorides', 'free sulfur dioxide',
       'total sulfur dioxide', 'density', 'pH', 'sulphates', 'alcohol',
       'quality'],
      dtype='str')
type                     0
fixed acidity           10
volatile acidity         8
citric acid              3
residual sugar           2
chlorides                2
free sulfur dioxide      0
total sulfur dioxide     0
density                  0
pH                       9
sulphates                4
alcohol                  0
quality                  0
dtype: int64
       fixed acidity  volatile acidity  citric acid  residual sugar  \
count    6487.000000       6489.000000  6494.000000     6495.000000   
mean        7.216579          0.339691     0.318722        5.444326   
std         1.296750          0.164649     0.145265        4.758125   
min         3.800000          0.080000     0.000000        0.600000   
25%         6.400000          0.230000     

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
count,6463.000000,6463.000000,6463.000000,6463.000000,6463.000000,6463.000000,6463.000000,6463.000000,6463.000000,6463.000000,6463.000000,6463.000000
mean,7.217755,0.339589,0.318758,5.443958,0.056056,30.516865,115.694492,0.994698,3.218332,0.531150,10.492825,5.818505
std,1.297913,0.164639,0.145252,4.756852,0.035076,17.758815,56.526736,0.003001,0.160650,0.148913,1.193128,0.873286
min,3.800000,0.080000,0.000000,0.600000,0.009000,1.000000,6.000000,0.987110,2.720000,0.220000,8.000000,3.000000
25%,6.400000,0.230000,0.250000,1.800000,0.038000,17.000000,77.000000,0.992330,3.110000,0.430000,9.500000,5.000000
50%,7.000000,0.290000,0.310000,3.000000,0.047000,29.000000,118.000000,0.994890,3.210000,0.510000,10.300000,6.000000
75%,7.700000,0.400000,0.390000,8.100000,0.065000,41.000000,156.000000,0.997000,3.320000,0.600000,11.300000,6.000000
max,15.900000,1.580000,1.660000,65.800000,0.611000,289.000000,440.000000,1.038980,4.010000,2.000000,14.900000,9.000000


In [19]:
print(df.dtypes)
le=LabelEncoder()
df['type']=le.fit_transform(df['type'])
ratios = [(0.1,"90-10"),(0.2,"80-20"),(0.3,"70-30"),(0.4,"60-40")]
print(df.dtypes)

type                      int64
fixed acidity           float64
volatile acidity        float64
citric acid             float64
residual sugar          float64
chlorides               float64
free sulfur dioxide     float64
total sulfur dioxide    float64
density                 float64
pH                      float64
sulphates               float64
alcohol                 float64
quality                   int64
dtype: object
type                      int64
fixed acidity           float64
volatile acidity        float64
citric acid             float64
residual sugar          float64
chlorides               float64
free sulfur dioxide     float64
total sulfur dioxide    float64
density                 float64
pH                      float64
sulphates               float64
alcohol                 float64
quality                   int64
dtype: object


In [21]:
X=df.drop('quality',axis=1).values
y=df['quality'].values
for ratio,text in ratios:
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=ratio, random_state=42)
    gnb = GaussianNB()
    gnb.fit(X_train, y_train)
    predicted = gnb.predict(X_test)
    print(f"Classification report for {text} split\n {classification_report(y_test, predicted,zero_division=0)}")
    print(f"Confusion matrix for {text} split\n {confusion_matrix(y_test, predicted)}")
    print(f"Accuracy for {text} split = {accuracy_score(y_test, predicted)}\n\n")
    print("_"*100)

Classification report for 90-10 split
               precision    recall  f1-score   support

           0       0.20      0.33      0.25         3
           1       0.20      0.09      0.12        23
           2       0.55      0.49      0.52       212
           3       0.45      0.37      0.41       275
           4       0.26      0.31      0.28       109
           5       0.11      0.04      0.06        25
           6       0.00      0.00      0.00         0

    accuracy                           0.38       647
   macro avg       0.25      0.23      0.23       647
weighted avg       0.43      0.38      0.40       647

Confusion matrix for 90-10 split
 [[  1   0   2   0   0   0   0]
 [  2   2  11   6   2   0   0]
 [  1   3 103  84  19   0   2]
 [  0   4  63 102  66   4  36]
 [  1   1   9  30  34   4  30]
 [  0   0   0   5  12   1   7]
 [  0   0   0   0   0   0   0]]
Accuracy for 90-10 split = 0.3755795981452859


________________________________________________________________