# Data Science Packages - Lab Record
NumPy, Pandas, Scikit-learn, Keras

## NUMPY

### 1. Creating arrays
Creates 1D array from list.

In [3]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


### 2. Array shape and reshape
Reshape changes dimensions; shape shows current dimensions.

In [4]:
arr2d = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2d.shape)
reshaped = arr2d.reshape(3, 2)
print(reshaped)

(2, 3)
[[1 2]
 [3 4]
 [5 6]]


### 3. Array operations
Element-wise operations and dot product.

In [5]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(a + b)
print(a * b)
print(np.dot(a, b))

[5 7 9]
[ 4 10 18]
32


### 4. Random numbers
Generate random arrays from uniform and normal distributions.

In [11]:
rand_arr = np.random.rand(3, 3)
print(rand_arr)
normal = np.random.randn(5)
print(normal)

[[0.16103492 0.2749713  0.36030418]
 [0.15036453 0.08566485 0.67443887]
 [0.59457666 0.97616536 0.28868693]]
[ 0.47337701 -0.15658075 -0.1893566  -0.60360543  0.17496268]


### 5. Indexing and slicing
Access elements by index and slice arrays.

In [15]:
arr = np.arange(10)
print(arr[2:5])
print(arr[::2])
matrix = np.array([[1,2,3], [4,5,6]])
print(matrix[0, 2])

[2 3 4]
[0 2 4 6 8]
3


## PANDAS

### 1. Creating DataFrame
Create table from dictionary.

In [19]:
import pandas as pd
data = {'Name': ['Alice', 'Bob', 'Charlie'],
        'Age': [25, 30, 35],
        'Salary': [50000, 60000, 75000]}
df = pd.DataFrame(data)
print(df)

      Name  Age  Salary
0    Alice   25   50000
1      Bob   30   60000
2  Charlie   35   75000


### 2. Loading CSV
Read first 5 rows of CSV file.

In [17]:
df = pd.read_csv('data.csv')
print(df.head())
# Note: Uncomment if you have a CSV file to load

       Name  Age  Gender
0  Abhijith   22    Male
1   Abhinav   22    Male
2  Abhirami   22  Female
3     Adish   22    Male
4   Adithya   22    Male


### 3. Column operations
Access single column, multiple columns, create new column.

In [ ]:
print(df['Age'])
print(df[['Name', 'Salary']])
df['Bonus'] = df['Salary'] * 0.1
print(df)

0    25
1    30
2    35
Name: Age, dtype: int64
      Name  Salary
0    Alice   50000
1      Bob   60000
2  Charlie   75000
      Name  Age  Salary   Bonus
0    Alice   25   50000  5000.0
1      Bob   30   60000  6000.0
2  Charlie   35   75000  7500.0


### 4. Filtering rows
Select rows based on conditions.

In [24]:
filtered = df[df['Age'] <= 30]
print(filtered)
high_salary = df[df['Salary'] > 55000]
print(high_salary)

    Name  Age  Salary   Bonus
0  Alice   25   50000  5000.0
1    Bob   30   60000  6000.0
      Name  Age  Salary   Bonus
1      Bob   30   60000  6000.0
2  Charlie   35   75000  7500.0


### 5. Statistics
Summary statistics and aggregations.

In [27]:
print(df.describe())
print(df['Salary'].mean())
print(df['Age'].sum())

        Age        Salary        Bonus
count   3.0      3.000000     3.000000
mean   30.0  61666.666667  6166.666667
std     5.0  12583.057392  1258.305739
min    25.0  50000.000000  5000.000000
25%    27.5  55000.000000  5500.000000
50%    30.0  60000.000000  6000.000000
75%    32.5  67500.000000  6750.000000
max    35.0  75000.000000  7500.000000
61666.666666666664
90


## SCIKIT-LEARN

### 1. Train-test split
Divide data for training and testing.

In [29]:
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_iris
X, y = load_iris(return_X_y=True)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)
print(X_train.shape, X_test.shape)

(120, 4) (30, 4)


### 2. Decision Tree classifier
Train classifier and make prediction.

In [30]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.datasets import load_iris
X, y = load_iris(return_X_y=True)
clf = DecisionTreeClassifier()
clf.fit(X, y)
pred = clf.predict([[5.1, 3.5, 1.4, 0.2]])
print(pred)

[0]


### 3. Scaling features
Normalize features to 0 mean and unit variance.

In [33]:
from sklearn.preprocessing import StandardScaler
from sklearn.datasets import load_iris
X, y = load_iris(return_X_y=True)
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)
print(X_scaled[:2])

[[-0.90068117  1.01900435 -1.34022653 -1.3154443 ]
 [-1.14301691 -0.13197948 -1.34022653 -1.3154443 ]]


### 4. Model accuracy
Evaluate model performance on test data.

In [36]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
X, y = load_iris(return_X_y=True)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)
clf = DecisionTreeClassifier()
clf.fit(X_train, y_train)
accuracy = clf.score(X_test, y_test)
print(f"Accuracy: {accuracy}")

Accuracy: 1.0


### 5. Cross-validation
Test model across multiple data splits.

In [ ]:
from sklearn.model_selection import cross_val_score
from sklearn.tree import DecisionTreeClassifier
from sklearn.datasets import load_iris
X, y = load_iris(return_X_y=True)
clf = DecisionTreeClassifier()
scores = cross_val_score(clf, X, y, cv=5)
print(f"CV scores: {scores}, Mean: {scores.mean()}")

## KERAS

### 1. Sequential model
Create simple neural network architecture.

In [35]:
import keras
from keras.models import Sequential
from keras.layers import Dense
model = Sequential([
    Dense(10, activation='relu', input_dim=4),
    Dense(3, activation='softmax')
])
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])
print(model.summary())

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_2 (Dense)                 │ (None, 10)             │            50 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 3)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 83 (332.00 B)

 Trainable params: 83 (332.00 B)

 Non-trainable params: 0 (0.00 B)

None


### 2. Training model
Train network on data.

In [ ]:
import keras
from keras.models import Sequential
from keras.layers import Dense
from keras.datasets import mnist
(X_train, y_train), (X_test, y_test) = mnist.load_data()
X_train = X_train.reshape(-1, 784).astype('float32') / 255
X_test = X_test.reshape(-1, 784).astype('float32') / 255
model = Sequential([Dense(128, activation='relu', input_dim=784), Dense(10, activation='softmax')])
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])
model.fit(X_train, y_train, epochs=5, batch_size=32)

### 3. Model prediction
Predict on new data.

In [ ]:
predictions = model.predict(X_test[:5])
print(predictions)

### 4. Layers and activation
Build layer-by-layer, showing different activations.

In [ ]:
from keras.models import Sequential
from keras.layers import Dense
model = Sequential()
model.add(Dense(64, activation='relu', input_dim=10))
model.add(Dense(32, activation='relu'))
model.add(Dense(1, activation='sigmoid'))
print(model.summary())

### 5. Evaluation
Test trained model on test set.

In [ ]:
loss, accuracy = model.evaluate(X_test, y_test)
print(f"Loss: {loss}, Accuracy: {accuracy}")